services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://minio:9000/minio/health/live']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - minio-data:/data
  redis:
    image: redis:alpine3.18
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_REPLICATION_MODE=master
    command: >
      redis-server --save 20 1 --loglevel warning --requirepass redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:alpine3.21
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://mongo:mongo@localhost:27017/?authSource=mongo --quiet
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  redis-data:
  postgres-data:
  minio-data:
  mongodb-data:
