services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
            - "80:80/tcp"
        environment:
            TZ: 'America/La_Paz'
            WEBPASSWORD: 'admin'
            DNSMASQ_LISTENING: 'all'
            DNS_BOGUS_PRIV: true
        # Volumes store your data between container upgrades
        volumes:
            - './etc-pihole:/etc/pihole'
            - './etc-dnsmasq.d:/etc/dnsmasq.d'
        #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        cap_add:
            - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
        restart: unless-stopped
    caddy:
        image: caddy:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./site:/srv
            - caddy_data:/data
            - caddy_config:/config
    minio:
        image: minio/minio:latest
        container_name: minio
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /data --console-address ":9001"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        volumes:
            - minio-data:/data
    redis:
        image: redis:alpine3.18
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=redis
            - REDIS_REPLICATION_MODE=master
        command: >
            redis-server --save 20 1 --loglevel warning --requirepass redis
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        volumes:
            - redis-data:/data
    postgres:
        image: postgres:alpine3.21
        container_name: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        ports:
            - "9443:9443"
            - "8000:8000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        environment:
            TZ: 'America/La_Paz'
volumes:
    redis-data:
        driver: local
    postgres-data:
    minio-data:
    caddy_data:
    caddy_config:
    portainer_data:
