services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portainer.macmini.local
      - VIRTUAL_PORT=9000
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=America/La_Paz
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=America/La_Paz
    ports:
      - "8191:8191"
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./filebrowser:/config
      - /mnt/secondary:/srv #optional
    ports:
      - 8090:80
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - /mnt/secondary:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
    volumes:
      - ./bazarr:/config
      - /mnt/secondary/downloads/movies:/movies #optional
      - /mnt/secondary/downloads/tv-shows:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
    volumes:
      - ./radarr:/config
      - /mnt/secondary/movies:/movies #optional
      - /mnt/secondary:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
    volumes:
      - ./sonarr:/config
      - /mnt/secondary/tv:/tv #optional
      - /mnt/secondary:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
      - JELLYFIN_PublishedServerUrl=http://192.168.100.239 #optional
    volumes:
      - ./jellyfin:/config
      - /mnt/secondary/downloads/tv-shows:/data/tvshows
      - /mnt/secondary/downloads/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/La_Paz
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr:/app/config
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=35fedd414e15ebdbe94cb8e1c0c0535df40f519f90ce259382bc56a8bc112049
    ports:
      - '7575:7575'
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    ports:
      - '6050:3001'
    volumes:
      - /:/mnt/host:ro
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
    volumes:
      - ./ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped


volumes:
  caddy_data:
  caddy_config:
  portainer_data: