services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - '11434:11434'
    volumes:
      - ./ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  openwebui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: openwebui
    ports:
      - "3000:8080"
    volumes:
      - ./openwebui:/app/backend/data
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allow container to access host network
    runtime: nvidia  # Ensure it runs with GPU support (optional depending on setup)
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingLLM
    restart: unless-stopped
    ports:
      - '3001:3001'
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./anythingllm:/app/server/storage # Persistent storage
      - ./anythingllm/.env:/app/server/.env # Environment file
    environment:
      - STORAGE_DIR=/app/server/storage # Define storage path for app
    # litellm:
    #   image: ghcr.io/berriai/litellm:main-latest
    #   container_name: litellm
    #   restart: unless-stopped
    #   environment:
    #     - DATABASE_URL=postgresql://postgres:postgres@litellm-db:5432/postgres
    #     - UI_USERNAME=admin
    #     - UI_PASSWORD=admin
    #     - STORE_MODEL_IN_DB=true
    #     - LITELLM_MASTER_KEY=sk-J2A445oK9c0ZGqCLQVvD
    #     - LITELLM_SALT_KEY=sk-4ivoPRYdryn64Ax54NJ3

    #   ports:
    #     - '4000:4000'
    #   volumes:
    #     - ./litellm/config.yaml:/app/config.yaml
    #   healthcheck: # Defines the health check configuration for the container
    #     test: ['CMD', 'curl', '-f', 'http://litellm:4000/health/liveliness || exit 1'] # Command to execute for health check
    #     interval: 30s # Perform health check every 30 seconds
    #     timeout: 10s # Health check command times out after 10 seconds
    #     retries: 3 # Retry up to 3 times if health check fails
    #     start_period: 40s # Wait 40 seconds after container start before beginning health checks
    #   depends_on:
    #     - litellm-db
    # litellm-db:
    # image: postgres:16-alpine
    # container_name: litellm-db
    # restart: unless-stopped
    # healthcheck:
    #   test:
    #     - CMD-SHELL
    #     - pg_isready -U postgres -d postgres
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    # volumes:
    #   - ./litellm-db:/var/lib/postgresql/data:rw
    # environment:
    #   POSTGRES_DB: postgres
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
